# Generated by Django 3.1.2 on 2020-10-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mesa', models.CharField(max_length=20)),
                ('cc_pres', models.IntegerField(blank=True, null=True)),
                ('cc_dip', models.IntegerField(blank=True, null=True)),
                ('fpv_pres', models.IntegerField(blank=True, null=True)),
                ('fpv_dip', models.IntegerField(blank=True, null=True)),
                ('mts_pres', models.IntegerField(blank=True, null=True)),
                ('mts_dip', models.IntegerField(blank=True, null=True)),
                ('ucs_pres', models.IntegerField(blank=True, null=True)),
                ('ucs_dip', models.IntegerField(blank=True, null=True)),
                ('mas_pres', models.IntegerField(blank=True, null=True)),
                ('mas_dip', models.IntegerField(blank=True, null=True)),
                ('f21_pres', models.IntegerField(blank=True, null=True)),
                ('f21_dip', models.IntegerField(blank=True, null=True)),
                ('pdc_pres', models.IntegerField(blank=True, null=True)),
                ('pdc_dip', models.IntegerField(blank=True, null=True)),
                ('mnr_pres', models.IntegerField(blank=True, null=True)),
                ('mnr_dip', models.IntegerField(blank=True, null=True)),
                ('pan_pres', models.IntegerField(blank=True, null=True)),
                ('pan_dip', models.IntegerField(blank=True, null=True)),
                ('blancos_pres', models.IntegerField(blank=True, null=True)),
                ('blancos_dip', models.IntegerField(blank=True, null=True)),
                ('nulos_pres', models.IntegerField(blank=True, null=True)),
                ('nulos_dip', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'boleta',
                'verbose_name_plural': 'boletas',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dep', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_loc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rec', models.CharField(max_length=100)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votos.localidad')),
            ],
            options={
                'verbose_name': 'recinto',
                'verbose_name_plural': 'recintos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prov', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votos.departamento')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mun', models.CharField(max_length=50)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votos.provincia')),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votos.municipio'),
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jurado', models.CharField(max_length=50)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votos.boleta')),
            ],
            options={
                'verbose_name': 'jurado',
                'verbose_name_plural': 'jurados',
            },
        ),
        migrations.AddField(
            model_name='boleta',
            name='recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votos.recinto'),
        ),
    ]
